### ISSUE TITLE
Privateer WCU & Windows

### ISSUE THREAD

**Issue by KalRego** [ermo/privateer_wcu#2]
I managed to compile a windows executable, of the latest version (08.00) of Vegastrike!! And I am happy to report that, I got Privateer WCU to run, natively in Windows 10 x64, in a 1920x1080 resolution! 

There is a link posted in Vegastrike forums!!
https://forums.vega-strike.org/viewtopic.php?f=5&t=51646&start=50

It's quite rough around the edges, and I had to import settings from the Linux version, but it's playable. 

Is the original Privateer scenario playable to the end?

 And What about Righteus Fire?

Thank you for your time

**Comment by ermo** [comment]
Thanks for the report.

Both the original Privateer scenario and the Righteous Fire scenario should be there.

I've never personally played through it all on normal settings, as certain missions are way harder in the VS engine than in the original Privateer engine.

For future reference, please use the pwcu project for issues as this is now my "private" fork from which I do feature work and PRs.
